### PR TITLE
Additional Implementation

### PR DESCRIPTION
**Pull request by MotaOcimar**
#### Processors
- Implement RemoveHeader processor
- Implement SetBody processor
- Implement JsonMarshal and JsonUnmarshal processors
- Fix returning errors in the From processor

#### Http Producer
- Validate method passed as option in URI
- Make it possible to set the producer method and queries using Camel headers
- Producer forward Camel message body as http body

#### Http Consumer
- Forward queries and headers received by the consumer
- Restrict the consumer to only listen to the setted method, if setted

#### Other changes
- Start using go mod
- Implement a basic Simple Language
- Processors return the exchange resulting from their and their children's process to their parent
- Fail the exchange in case of error
- Bind default components in route creation

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@MotaOcimar thx for contributing, do you mind splitting up the pr if possible ? 
i.e. moving to modules could be a separate one

**Comment by MotaOcimar** [comment]
You mean separate the first commit in a different PR?

**Comment by lburgazzoli** [comment]
yes, it makes it easy to review the pr (given the limited amount of time I have)

**Comment by MotaOcimar** [comment]
Hey! Sorry for the delay, I was busy this beginning of the year. I hope you were able to review the PR properly

**Pull request merged**
